# Generated by Django 2.0.6 on 2018-06-26 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('addresses', models.CharField(max_length=200)),
            ],
        ),
    ]
